name: Release

on:
    push:
        tags:
            - '*'

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18

            - name: Build plugin
              run: npm ci && npm run build
              working-directory: ResetSequence.tableplusplugin

            - name: Make zip
              run: zip tableplus-reset-sequence-plugin-${GITHUB_REF_NAME}.zip ResetSequence.tableplusplugin/plugin.js ResetSequence.tableplusplugin/manifest.json

            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  files: tableplus-reset-sequence-plugin-*.zip